### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by mayank134819** [matheuss/google-translate-api#17] opened 2017-04-09 06:32 UTC
Error: Response code 503 (Service Unavailable)
    at /home/mayank/Desktop/node_modules/google-translate-token/index.js:103:25
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 'BAD_NETWORK',
  message: 'Response code 503 (Service Unavailable)'

 Error: getaddrinfo ENOTFOUND translate.google.com translate.google.com:443
    at /home/mayank/Desktop/node_modules/google-translate-token/index.js:103:25
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 'BAD_NETWORK',
  message: 'getaddrinfo ENOTFOUND translate.google.com translate.google.com:443'

**Comment by JukeboxRhino** [comment] 2017-04-14 06:42
I'm also getting this now. My previous fix had fixed the BAD_NETWORK error but now every request fails with this 503.

**Comment by eliavmaman** [comment] 2017-04-23 08:35
i'm getting that as well... any idea fellowes? :)

**Comment by teamsteamdev** [comment] 2017-05-06 15:13
While we're waiting for PR #16 to be merged, try this repo: [teamsteamdev/google-translate-api#2083](https://github.com/teamsteamdev/google-translate-api/tree/2083). I just ran `$ yarn test` and it passes for me. This branch incorporates PR #13 which allows for submitting longer text strings, and it should solve Issues #11, #5, #6, but YMMV.

I added it to `package.json` in one of my projects like below, and no problems so far...

    "dependencies": {
       "google-translate-api": "teamsteamdev/google-translate-api#2083"
    }

Good luck! @eliavmaman @JukeboxRhino  @tgyou @matheuss

**Comment by teamsteamdev** [comment] 2017-05-06 15:15
I have noticed that Google rejects strings including `\r`. If you're having problems, try looking at the string you're passing for translation. I'm splitting my submissions into paragraphs and submitting them separately using `Promise.all()`.

**Comment by AStoker** [comment] 2017-06-02 18:24
This issue is a duplicate of https://github.com/matheuss/google-translate-api/issues/11

**Comment by JukeboxRhino** [comment] 2017-06-27 20:50
Duplicate of #11

**Closed by JukeboxRhino** 2017-06-27 20:50 UTC
